### ISSUE TITLE
getInt()

### ISSUE THREAD

**Issue by CupidonSauce173** [jasonwynn10/MiniBosses#4] opened 2018-07-27 20:20 UTC
[20:19:46] [Server thread/CRITICAL]: Unhandled exception executing command 'minibosses spawn test' in minibosses: Call to a member function getInt() on null
[20:19:46] [Server thread/CRITICAL]: Error: "Call to a member function getInt() on null" (EXCEPTION) in "MiniBosses-master/src/MiniBosses/Boss" at line 54

**Comment by jasonw4331** [comment] 2018-07-27 21:47
duplicate of #3 
duplicate of #1 
fixed in 9621a64a9f73b479b862429677707009169a0f7f

**Closed as completed by jasonw4331** 2018-07-27 21:47 UTC
